### ISSUE TITLE
Pointers to simple types are not rendered as valid Go

### ISSUE THREAD

**Issue by twpayne** [sanity-io/litter#35]
Consider the example:

```go
package main

import (
	"github.com/sanity-io/litter"
)

type T struct {
	I *int
}

func main() {
	i := 0
	t := T{
		I: &i,
	}
	litter.Dump(t)
}
```

This prints:

```go
main.T{
  I: &0,
}
```

which is not valid Go.

When the type of a field is a simple type, like `int`, `string`, `float64`, etc. I would suggest that litter prints:

```go
main.T{
  I: litter.Int(0),
}
```

where `litter.Int` is defined as:

```go
package litter

func Int(i int) *int { return &i }
```

Similarly for other types.

**Comment by twpayne** [comment]
Would you accept a PR that implements this?

**Comment by atombender** [comment]
I agree that it's not valid and not ideal, but I also think that Litter shouldn't be a "dependency" in any dumped output. The point of Litter isn't to be compilable. There are situations (such as cyclic data structures) where it definitely isn't.

A special mode where Litter did produce compilable code would be cool, in which case I'd probably prefer this output instead (which has no external dependencies):

```go
main.T{
  I: (func(v int) *int { return &v })(0),
}
```

Also, keep in mind that primitives can be aliased. For example:

```go
type myint int
type T struct {
	I *myint
}
```

Now you wouldn't be able to use your hypothetical `litter.Int()` function, because it'd have to be something like:

```go
main.T{
  I: (func(v myint) *myint { return &v })(0),
}
```

**Comment by twpayne** [comment]
Very good points and suggestions. The no-dependency output makes a lot of sense.

Would you like a PR that implements this, or would you prefer to implement this yourself?

**Comment by atombender** [comment]
I'd accept a PR, sure. I think need should be under a "strict Go" mode flag.
