### ISSUE TITLE
feature request: Dumper interface

### ISSUE THREAD

**Issue by astec** [sanity-io/litter#6]
Define interface that could be implemented for custom dumping.

Something like:
```
type Dumper interface {
	Dump(w io.Writer)
}
```

Can be useful for []byte, *json.RawMessage, user types, etc.

**Comment by atombender** [comment]
I suggest that this be renamed to something less generic, like `LitterDump` or `DumpLitter` or `Litteralize`, just to be explicit. Due to the way Go interfaces work, if any other library unrelated to Litter uses an interface `Dump(io.Writer)`, it will be ambiguous on the implementor end what you're implementing your method for, and it might conflict.
